name: Nginx Build
on: push
jobs:
  RPM-build:
    name: Build RPMs
    runs-on: ubuntu-latest
    steps:
        - name: Check out
          uses: actions/checkout@v2
        - name: Docker build
          run: docker build -f ./Dockerfile.centos -t brobird/nginx:centos .
        - name: Docker run and collect RPMs
          run: docker run -d -v /tmp/rpm:/nginx-builder brobird/nginx:centos
        - name: Upload Release
          uses: softprops/action-gh-release@v1
          if: startsWith(github.ref, 'refs/tags/')
          env:
            GITHUB_TOKEN: ${{ secrets. GH_TOKEN }}
          with:
            files: /tmp/rpm/*.rpm
            draft: false
            prerelease: false
  DEB-build:
    name: Build DEBs
    runs-on: ubuntu-latest
    steps:
        - name: Check out
          uses: actions/checkout@v2
        - name: Docker build
          run: docker build -f ./Dockerfile.ubuntu -t brobird/nginx:ubuntu .
        - name: Docker run and collect DEBs
          run: docker run -d -v /tmp/deb:/nginx-builder brobird/nginx:ubuntu
        - name: Upload Release
          uses: softprops/action-gh-release@v1
          if: startsWith(github.ref, 'refs/tags/')
          env:
            GITHUB_TOKEN: ${{ secrets. GH_TOKEN }}
          with:
            files: /tmp/deb/*.deb
            draft: false
            prerelease: false

